import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";
import Menu from "@/components/navbar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div id="Page">
          <Menu />
          {children}
        </div>
      </body>
    </html>
  );
}


function Header() {
  return (
    <header id="Header">
      <a href="/">
        <h1>Fachschaft Geoinformatik Münster</h1>
      </a>
    </header>
  )
}
